-- Create sys-admin ACL
INSERT INTO
    AccessControlList (id, description, updaterACLId, isOpen)
VALUES
    ('sys-admin', 'write-description', 'sys-admin', 0);

-- Add member user to sys-admin ACL
INSERT INTO
    ACLMembership (parentACLId, memberACLId, memberUserId)
VALUES
    ('sys-admin', NULL, 'fake_joy');

-- Insert course metadata
INSERT INTO
    courseMetadata (
        courseId,
        instanceId,
        lectureSchedule,
        tutorialSchedule,
        seriesId,
        hasHomework,
        hasQuiz,
        updaterId,
        universityId,
        courseName,
        notes,
        landing,
        slides,
        teaser,
        instructors
    )
VALUES
    (
        'ai-1',
        'WS25-26',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Artificial Intelligence I',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=notes1&l=en',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=coursepage1&l=en',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=slides1&l=en',
        'A classical course on symbolic artificial intelligence covering the whole range of methods from search-based problem solving, via constraint propagation and logical/formal methods to planning.',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'ai-2',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Artificial Intelligence II',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=notes2&l=en',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=coursepage2&l=en',
        'https://mathhub.info?a=courses/FAU/AI/course&p=course/notes&d=slides2&l=en',
        'A classical course on statistical and subsymbolic artificial intelligence covering the whole range of methods from reasoning with uncertainty, decision theory, MDPs and POMDPs to machine learning and natural language processing.',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'gdp',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Grundlagen der Programmierung',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/FAU/GDP/course&p=course/notes&d=notes&l=en',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/FAU/GDP/course&p=course/notes&d=coursepage&l=en',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/FAU/GDP/course&p=course/notes&d=slides&l=en',
        NULL,
        JSON_ARRAY ('Vanessa Klein')
    ),
    (
        'iwgs-1',
        'WS25-26',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Informatische Werkzeuge für die Geistes- und Sozialwissenschaften I',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=notes-part1&l=en',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=coursepage1&l=en',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=slides-part1&l=en',
        'This course introduces computational tools for the humanities and social studies...',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'iwgs-2',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Informatische Werkzeuge für die Geistes- und Sozialwissenschaften II',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=notes-part2&l=en',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=coursepage2&l=en',
        'https://mathhub.info?a=courses/FAU/IWGS/course&p=course/notes&d=slides-part2&l=en',
        'This course continues the introduction...',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'krmt',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Knowledge Representation of Mathematical Theories',
        'https://mathhub.info?a=courses/FAU/KRMT/course&p=dennis/course&d=notes&l=en',
        'https://mathhub.info?a=courses/FAU/KRMT/course&p=dennis/course&d=coursepage&l=en',
        'https://mathhub.info?a=courses/FAU/KRMT/course&p=dennis/course&d=slides&l=en',
        '<p>This repository contains the sources for the notes...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'lbs',
        'WS25-26',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Logic-Based Natural Language Semantics',
        'https://mathhub.info?a=courses/FAU/LBS/course&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/FAU/LBS/course&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/FAU/LBS/course&p=course/notes&d=slides&l=en',
        'This course covers the construction of logic-based models...',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'smai',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'FAU',
        'Symbolic Methods for Artificial Intelligence',
        'https://mathhub.info?a=courses/FAU/SMAI/course&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/FAU/SMAI/course&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/FAU/SMAI/course&p=course/notes&d=slides&l=en',
        'This course introduces the scientific methods...',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'acs',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'Advanced Computer Science (Fragment)',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/Jacobs/ACS/course&p=course/notes&d=notes&l=en',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/Jacobs/ACS/course&p=course/notes&d=coursepage&l=en',
        'https://stexmmt.mathhub.info/:sTeX?a=courses/Jacobs/ACS/course&p=course/notes&d=slides&l=en',
        NULL,
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'comsem',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'Computational Semantics of Natural Language',
        'https://mathhub.info?a=courses/Jacobs/ComSem&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/Jacobs/ComSem&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/Jacobs/ComSem&p=course/notes&d=slides&l=en',
        '<p>This repository contains the sources ...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'complog',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'Computational Logic',
        'https://mathhub.info?a=courses/Jacobs/CompLog&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/Jacobs/CompLog&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/Jacobs/CompLog&p=course/notes&d=slides&l=en',
        '<p>This repository contains the sources...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'gencs i',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'General Computer Science I',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=notes1&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=coursepage1&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=slides1&l=en',
        '<p>This repository contains the sources...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'gencs ii',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'General Computer Science II',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=notes2&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=coursepage2&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenCS/course&p=course/notes&d=slides2&l=en',
        '<p>This repository contains the sources...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'genict',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'General Information and Communication Technology',
        'https://mathhub.info?a=courses/Jacobs/GenICT/course&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenICT/course&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/Jacobs/GenICT/course&p=course/notes&d=slides&l=en',
        NULL,
        JSON_ARRAY ('Michael Kohlhase')
    ),
    (
        'tdm',
        'dummy_sem',
        '[]',
        NULL,
        NULL,
        FALSE,
        FALSE,
        'fake_joy',
        'Jacobs',
        'Text and Digital Media',
        'https://mathhub.info?a=courses/Jacobs/TDM/course&p=course/notes&d=notes&l=en',
        'https://mathhub.info?a=courses/Jacobs/TDM/course&p=course/notes&d=coursepage&l=en',
        'https://mathhub.info?a=courses/Jacobs/TDM/course&p=course/notes&d=slides&l=en',
        '<p>This repository contains the sources...</p>',
        JSON_ARRAY ('Michael Kohlhase')
    );