allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  '@swc/core': true
  bcrypt: true
  canvas: true
  core-js-pure: true
  cypress: true
  esbuild: true
  less: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - cypress

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - bcrypt
  - core-js-pure
  - esbuild
  - less
  - nx
  - prisma
  - sharp
  - unrs-resolver
