-- Staging row timestamps. ON UPDATE so raw SQL upserts bump updatedAt.

ALTER TABLE `unverifiedUsers`
  ADD COLUMN `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
